export const CARD = {
    ROOT_MAX_WIDTH : 345,
    ROOT_MIN_WIDTH : 345,
    ROOT_MAX_HEIGHT : "42vh",
    
    ROOT_TRANSITION_DURATION: "0.5s",
    ROOT_ANIMATION_DURATION: "1s",
    TEXT_DESC_ANIMATION_DURATION: "0.25s",
    TEXT_DESC_OPACITY: 0.75,

    CANCEL_DETAIL_BUTTON_BGCOLOR: "rgba(255,255,255,1)",
    CANCEL_DETAIL_BUTTON_FONT_SIZE: "xx-large",
    CANCEL_DETAIL_BUTTON_PADDING: "20PX",
    CANCEL_DETAIL_BUTTON_TRANSFORM: "translateX(90vw) rotate(45deg)",
    CANCEL_DETAIL_BUTTON_BORDER_RADIUS: "50%",
    CANCEL_DETAIL_BUTTON_HOVER_BGCOLOR: "white",
    CANCEL_DETAIL_BUTTON_HOVER_OPACITY: 0.5,
    CANCEL_DETAIL_BUTTON_BORDER_SHADOW: "10px 10px 10px 10px black",

    SHOW_DETAIL_POSITION: "absolute",
    SHOW_DETAIL_TOP:"44%"
};


export const POSITION_ABS = {
    LIKED_X: 54.19,
    LIKED_Y: 21,
    BLOCK_X: 75.86,
    BLOCK_Y: 21,
}

