export const CARD = {
    ROOT_MAX_WIDTH : 345,
    ROOT_MIN_WIDTH : 345,
    ROOT_TRANSITION_DURATION: "0.5s",
    ROOT_ANIMATION_DURATION: "1s",
    TEXT_DESC_ANIMATION_DURATION: "0.25s",
    TEXT_DESC_OPACITY: 0.75,
};

